build:
  image: registry.hamdocker.ir/mlsd-indicatorss/stockprediction/runner:v1.1
  only:
    refs:
    - master
  script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD $REGISTRY 
    - make docker-build
    - make docker-push

  stage: build

test:  
  image: registry.hamdocker.ir/mlsd-indicatorss/stockprediction/runner:v1.1
  only:
    refs:
    - master
  script:
    - python test_app.py
  stage: test

deploy:
  image: registry.hamdocker.ir/mlsd-indicatorss/stockprediction/runner:v1.1
  only:
    refs:
    - master
  script:
    - make darkube-deploy
  stage: deploy