build:
  image: registry.hamdocker.ir/mlsd-indicatorss/stockprediction/runner:v1.1
  only:
    refs:
    - master
  script:
    - ls
    # - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD $REGISTRY 
    # - make docker-build
    # - make docker-push
  stage: build

deploy:
  image: registry.hamdocker.ir/mlsd-indicatorss/stockprediction/runner:v1.1
  only:
    refs:
    - master
  script:
    - make docker-deploy
  stage: deploy