build:
  image: registry.hamdocker.ir/mlsd-indicatorss/stockprediction/runner:v1.1
  only:
    refs:
    - master
  script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD $REGISTRY 
    - make docker-build
    - make docker-push
  stage: build

deploy:
  image: registry.hamdocker.ir/mlsd-indicatorss/stockprediction/runner:v1.1
  only:
    refs:
    - master
  script:
    - 'darkube deploy --token ${DEPLOY_TOKEN}
      --app-id ${APP_ID}  --image-tag "${CI_COMMIT_SHORT_SHA}"
      --job-id "${CI_JOB_ID}"'
  stage: deploy