darkube_build_test-app_asghar:
  image: hamravesh.hamdocker.ir/public/darkube-cli:v1.1
  only:
    refs:
    - master
  script:
    - python readAsghar.py
  stage: build
darkube_deploy_test-app_asghar:
  image: hamravesh.hamdocker.ir/public/darkube-cli:v1.1
  only:
    refs:
    - master
  script:
    - 'darkube deploy --token ${DEPLOY_TOKEN}
      --app-id ${APP_ID}  --image-tag "${CI_COMMIT_SHORT_SHA}"
      --job-id "${CI_JOB_ID}"'
  stage: deploy