apiVersion: v1
kind: Service
metadata:
  name: ingress-controller-service
  annotations:
    # Add any necessary annotations specific to your Ingress controller
    # For example, for Nginx Ingress Controller, you can use:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  type: NodePort
  ports:
    - port: 80  # Replace with the port you want to expose
      targetPort: 80  # Replace with the Ingress controller's target port
      nodePort: 30080  # Replace with the desired NodePort value
  selector:
    # Add the appropriate selector to match the Ingress controller deployment
    # For example, for Nginx Ingress Controller, you can use:
    app: ingress-nginx