global:
    scrape_interval: 5s
    external_labels:
        monitor: 'my-monitor'
scrape_configs:
    - job_name: 'prometheus'
      static_configs:
          - targets: ['0.0.0.0:9090']

    - job_name: 'my-metrics'
      scrape_interval: 5s
      static_configs:
          - targets: ['213.233.184.137:8080']